# Core Colors
background            #0f1417
foreground            #dfe3e7
selection_foreground  #8fcff3
selection_background  #003549
cursor                #8fcff3
cursor_text_color     #0f1417

# Regular Colors
color0  #0f1417
color1  #ffb4ab
color2  #8fcff3
color3  #c9c1ea
color4  #c3e8ff
color5  #d1e5f3
color6  #b5c9d7
color7  #dfe3e7

# Bright Colors
color8  #353a3d
color9  #ffb4ab
color10 #8fcff3
color11 #c9c1ea
color12 #c3e8ff
color13 #d1e5f3 
color14 #b5c9d7
color15 #dfe3e7
